### ISSUE TITLE
Cannot read property 'newLine' of undefined

### ISSUE THREAD

**Issue by axionmak** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#105]
Hi,

i try to compile the latest version in angular2 of core ui but i run into the following error at build

> ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (C:\Repository\_opensource\CoreUI-Free-Bootstrap-Admin-Template\Angular2_CLI_Full_Project\node_modules\typescript\lib\typescript.js:9144:20)
    at Object.createCompilerHost (C:\Repository\_opensource\CoreUI-Free-Bootstrap-Admin-Template\Angular2_CLI_Full_Project\node_modules\typescript\lib\typescript.js:59057:26)
    at Object.ngcLoader (C:\Repository\_opensource\CoreUI-Free-Bootstrap-Admin-Template\Angular2_CLI_Full_Project\node_modules\@ngtools\webpack\src\loader.js:329:31)
 @ multi ./src/main.ts

i'm running node v6.9.5 and npm v4.1.2

Regards

**Comment by santonica** [comment]
Same issue for me as well.
Trying to run ng serve with angular 2.4.6 causes the following error.
I am using node v6.9.4 and npm 4.2.0
Angular CLI is 1.0.0-beta.31

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (<My-Directory>\node_modules\typescript\lib\typescript.js:9426:20)
    at Object.createCompilerHost (<My-Directory>\node_modules\typescript\lib\typescript.js:62475:26)
    at Object.ngcLoader (<My-Directory>\node_modules\@ngtools\webpack\src\loader.js:341:33)
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
webpack: Failed to compile.

**Comment by QuantumInformation** [comment]
me two with angular 2.3.1

**Comment by mrholek** [comment]
If you have this issue you should do:
1. Re-install angular cli
2. Remove and install node_components

**Comment by thiagolimaa** [comment]
The issue was solved after updating the `package.json` `"@angular/cli": "1.0.0-rc.0"` *new*, remember if it's an old project it may be like that: `"angular-cli": "1.0.0-beta.24"`*old*.

**Comment by TobEnd** [comment]
`npm uninstall --save-dev angular-cli
npm install --save-dev @angular/cli@latest`

should fix everything

**Comment by Arvraepe** [comment]
Does not fix the issue on my machine :(
