### ISSUE TITLE
Angular2_CLI_Starter issue

### ISSUE THREAD

**Issue by hyygavin1990** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#107]
lang.js:130Angular is running in the development mode. Call enableProdMode() to enable the production mode.
error_handler.js:54EXCEPTION: Uncaught (in promise): Error: Cannot find module './src/app/dashboard/dashboard.module'.
Error: Cannot find module './dashboard/dashboard.module'.
    at new Error (native)
    at webpackEmptyContext (http://localhost:4200/main.bundle.js:7:8) [angular]
    at SystemJsNgModuleLoader.loadAndCompile (http://localhost:4200/vendor.bundle.js:71909:40) [angular]
    at SystemJsNgModuleLoader.load (http://localhost:4200/vendor.bundle.js:71897:60) [angular]
    at RouterConfigLoader.loadModuleFactory (http://localhost:4200/vendor.bundle.js:22189:128) [angular]
    at RouterConfigLoader.load (http://localhost:4200/vendor.bundle.js:22176:81) [angular]
    at MergeMapSubscriber.project (http://localhost:4200/vendor.bundle.js:75517:111) [angular]
    at MergeMapSubscriber._tryNext (http://localhost:4200/vendor.bundle.js:22392:27) [angular]
    at MergeMapSubscriber._next (http://localhost:4200/vendor.bundle.js:22382:18) [angular]
    at MergeMapSubscriber.Subscriber.next (http://localhost:4200/vendor.bundle.js:6518:18) [angular]
    at ScalarObservable._subscribe (http://localhost:4200/vendor.bundle.js:59455:24) [angular]
    at ScalarObservable.Observable._trySubscribe (http://localhost:4200/vendor.bundle.js:5747:25) [angular]
    at ScalarObservable.Observable.subscribe (http://localhost:4200/vendor.bundle.js:5735:27) [angular]
    at MergeMapOperator.call (http://localhost:4200/vendor.bundle.js:22357:23) [angular]

## Cannot find module './dashboard/dashboard.module'. 
When I use 'ng serve' to start testing,browser's console is always outputing this error.Can you help me to solve this problem?Thank you.

**Comment by cfangxx** [comment]
me too~!

**Comment by zhudui** [comment]
you can go to app.routing.ts and replace the routes with the following code:
`export const routes: Routes = [
  {
    path: '',
    component: FullLayoutComponent,
    data: {
      title: 'Home'
    },
    children: [
      {
        path: '',
        redirectTo: 'dashboard',
        pathMatch: 'full',
      },
      {
        path: 'dashboard',
        loadChildren: './dashboard/dashboard.module#DashboardModule'
      },
    ]
  }
];`

**Comment by zhudui** [comment]
you can go to app.routing.ts and replace the routes with the following code:
`export const routes: Routes = [

  {

    path: '',

    component: FullLayoutComponent,

    data: {

      title: 'Home'

    },

    children: [

      {

        path: '',

        redirectTo: 'dashboard',

        pathMatch: 'full',

      },

      {

        path: 'dashboard',

        loadChildren: './dashboard/dashboard.module#DashboardModule'

      },

    ]

  }

];`

**Comment by zhudui** [comment]
you can go to app.routing.ts and replace the routes with the following code:
`export const routes: Routes = [
  {
    path: '',
    component: FullLayoutComponent,
    data: {
      title: 'Home'
    },
    children: [
      {
        path: '',
        redirectTo: 'dashboard',
        pathMatch: 'full',
      },
      {
        path: 'dashboard',
        loadChildren: './dashboard/dashboard.module#DashboardModule'
      },
    ]
  }
];`

**Comment by zhudui** [comment]
you can go to app.routing.ts and replace the routes with the following code:
`export const routes: Routes = [
  {
    path: '',
    component: FullLayoutComponent,
    data: {
      title: 'Home'
    },
    children: [
      {
        path: '',
        redirectTo: 'dashboard',
        pathMatch: 'full',
      },
      {
        path: 'dashboard',
        loadChildren: './dashboard/dashboard.module#DashboardModule'
      },
    ]
  }
];`
