### ISSUE TITLE
ERROR in AppModule is not an NgModule

### ISSUE THREAD

**Issue by alouane** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#108]
Hi, I got this weird error right after running ng serve

`ERROR in AppModule is not an NgModule ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (C:\Users\aloua\Documents\AngularApps\ChoufTvPlus-Front\Angular2_CLI_Starter\node_modules\typescript\lib\typescript.js:9420:20)
    at Object.createCompilerHost (C:\Users\aloua\Documents\AngularApps\ChoufTvPlus-Front\Angular2_CLI_Starter\node_modules\typescript\lib\typescript.js:62469:26)
    at Object.ngcLoader (C:\Users\aloua\Documents\AngularApps\ChoufTvPlus-Front\Angular2_CLI_Starter\node_modules\@ngtools\webpack\src\loader.js:341:33)
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts`

Any help is appreciated

**Comment by alouane** [comment]
After installing angular-cli@1.0.0-beta.11-webpack.8 version everything was fixed
Closing now, I hope it helps someone facing the same issue
Cheers
