### ISSUE TITLE
Issue with running Angular CLI Full Project

### ISSUE THREAD

**Issue by mastarenee** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#126]
When I run ng serve I get the following error:

My node and npm versions are: 4.3.0

C:\Users\Username\applications\app\devtest\adminpanel\panel>ng serve
C:\Users\Username\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@ng
tools\json-schema\src\schema-class-factory.js:34
            result.push(...indices);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Username\AppData\Roaming\npm\node_modules\a
ngular-cli\node_modules\@ngtools\json-schema\src\index.js:3:30)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by jabas06** [comment]
You're using outdated packages. Install node 6.X and the latest angular cli (npm install -g @angular/cli)

**Comment by mastarenee** [comment]
Thanks, that worked. I used it last month using the same version so I was wondering what happened.
