### ISSUE TITLE
React.js Projects not Building

### ISSUE THREAD

**Issue by GQAdonis** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#159]
I see that the React.js projects have been updated in just the last 2 hours and are not currently building in the master branch.  Do you have an estimated time that this will be available?

**Comment by mrholek** [comment]
I will check it tomorrow

**Comment by mrholek** [comment]
I just checked it and everything is ok.

**Comment by prionkor** [comment]
Unable to run react example

Terminal error
---------------

```
npm run start

> coreui-react@1.0.0-alpha.6 start /home/sisir/static-projects/core-ui/React_Full_Project
> react-scripts start

sh: 1: react-scripts: not found

npm ERR! Linux 4.8.0-52-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! coreui-react@1.0.0-alpha.6 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the coreui-react@1.0.0-alpha.6 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the coreui-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs coreui-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls coreui-react
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sisir/.npm/_logs/2017-05-27T21_13_24_577Z-debug.log

```
LOG
----

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle coreui-react@1.0.0-alpha.6~prestart: coreui-react@1.0.0-alpha.6
6 silly lifecycle coreui-react@1.0.0-alpha.6~prestart: no script for prestart, continuing
7 info lifecycle coreui-react@1.0.0-alpha.6~start: coreui-react@1.0.0-alpha.6
8 verbose lifecycle coreui-react@1.0.0-alpha.6~start: unsafe-perm in lifecycle true
9 verbose lifecycle coreui-react@1.0.0-alpha.6~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/sisir/static-projects/core-ui/React_Full_Project/node_modules/.bin:/home/sisir/bin:/home/sisir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle coreui-react@1.0.0-alpha.6~start: CWD: /home/sisir/static-projects/core-ui/React_Full_Project
11 silly lifecycle coreui-react@1.0.0-alpha.6~start: Args: [ '-c', 'react-scripts start' ]
12 info lifecycle coreui-react@1.0.0-alpha.6~start: Failed to exec start script
13 verbose stack Error: coreui-react@1.0.0-alpha.6 start: `react-scripts start`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid coreui-react@1.0.0-alpha.6
15 verbose cwd /home/sisir/static-projects/core-ui/React_Full_Project
16 error Linux 4.8.0-52-generic
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 error node v7.10.0
19 error npm  v4.2.0
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error coreui-react@1.0.0-alpha.6 start: `react-scripts start`
24 error spawn ENOENT
25 error Failed at the coreui-react@1.0.0-alpha.6 start script 'react-scripts start'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the coreui-react package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     react-scripts start
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs coreui-react
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls coreui-react
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
27 warn Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by prionkor** [comment]
Make sure you run `npm install` or `yarn install`
