### ISSUE TITLE
Exception Thrown TabsetConfig!

### ISSUE THREAD

**Issue by wuno** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#95]
I have been using this seed project for a good while now. Throughout the time I have obviously made some modifications to the project. Currently I use the `<aside class="aside-menu">` which lives inside the` full-layout.component.html` file. 

This is the HTML for the aside menu. That is the menu that slides out from the right side and have a directive controlling its toggle. 

I took the aside menu html out of my full-layout.component.html a while back and then attached it to a selector. Which is how I attach it to the component now. So it looks like this,

```
<!-- Aside Menu -->
<application-aside></application-aside>
<!-- End Aside Menu -->

```

Then of course I create the selector,

```
@Component({
    selector: 'application-aside',
    templateUrl: './aside.component.html'
})
export class AsideComponent {
	   constructor( private router: Router, private auth: Auth  ) { }

}

```

This has worked for me for months but now I get this error,

> EXCEPTION: Uncaught (in promise): Error: Error in ./AsideComponent class AsideComponent - inline template:1:4 caused by: No provider for TabsetConfig!

So I do some research and notice we do not have `ng2-tabs` in the app. So install that. But then I realize that they have a new version which is called `ngx-tabs`, so I install that. Now after making sure I am importing the correct TabsModule into my app,

app.module.ts
`import { TabsModule }                       from "ngx-tabs";`

The error that I get after everything is a conflict of `selectors`. But I can not find any reason why this would be happening,

> Unhandled Promise rejection: Template parse errors:
> More than one component matched on this element.
> Make sure that only one component's selector can match a given element.
> Conflicting components: TabsetComponent,Tabset ("<aside class="aside-menu">
>     [ERROR ->]<tabset>
>         <tab>
>             <template tabHeading><i class="fa fa-list"></i>
> "): AsideComponent@1:4 ; Zone: <root> ; Task: Promise.then ; Value: 
> SyntaxError
> __zone_symbol__error
> :
> Error: Template parse errors: More than one component matched on this element. Make sure that only one component's selector can match a given element. Conflicting components: TabsetComponent,Tabset ("<aside class="aside-menu"> [ERROR ->]<tabset> <tab> <template tabHeading><i class="fa fa-list"></i> "): AsideComponent@1:4 at SyntaxError.ZoneAwareError (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:6616:1), <anonymous>:811:33) at SyntaxError.BaseError [as constructor] (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:4364:1), <anonymous>:29:16) at new SyntaxError (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:258:1), <anonymous>:162:16) at TemplateParser.parse (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:796:1), <anonymous>:169:19) at JitCompiler._compileTemplate (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:2182:1), <anonymous>:378:68) at eval (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:2182:1), <anonymous>:261:62) at Set.forEach (native) at JitCompiler._compileComponents (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:2182:1), <anonymous>:261:19) at createResult (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:2182:1), <anonymous>:144:19) at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:6616:1), <anonymous>:242:26) at Zone.run (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:6616:1), <anonymous>:113:43) at eval (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:6616:1), <anonymous>:535:57) at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:6616:1), <anonymous>:275:35) at Zone.runTask (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:6616:1), <anonymous>:151:47) at drainMicroTaskQueue (eval at <anonymous> (http://localhost:4200/js/app/bundle.js:6616:1), <anonymous>:433:35)

I believe now what the problem is, is that there is a conflict between the ng2 or ngx-tabs I added to the project and the ng2-bootstrap which has TabsetComponent inside of it. 

So this raises the question, If we need a way to clear

>  No provider for TabsetConfig

Then I assume we won't have to install the tabs modules which leaves error 2 out of the equation.

Does anyone have any knowledge about issue with tabs, tabsetconfig or tabset? Are we using ngx-tabs or ng2-tabs now? Does it make a difference?

**Comment by wuno** [comment]
This problem does have a solution. Also it is indeed in the docs. If anyone runs into this issue here is everything you need to know. 

The tabs [documentation](http://valorkin.github.io/ng2-bootstrap/#/tabs) explains how to import,

I was able to solve this without installing the other modules. Evidently you can import tabs from ng-bootstrap. So it looks like this,

```
// Import from ng-bootstrap
import { Ng2BootstrapModule }               from 'ng2-bootstrap';
import { TabsModule }                              from 'ng2-bootstrap';

import { ChartsModule }                           from 'ng2-charts/ng2-charts';

@NgModule({
    declarations: [
        AppComponent,
        HomeComponent
    ],
    imports: [
        TabsModule.forRoot()
    ],
    providers: [ 
        Guard
    ],
    bootstrap: [AppComponent]
})
```

Once I imported from `ng-bootstrap` and added the `.forRoot()` part to the imports everything worked fine. I was also able to remove the extra modules I installed. They were not needed. 

If you still need more information you can see [this here](https://github.com/valor-software/ng2-bootstrap/issues/1547#issuecomment-2748).
